# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5412a64d4cc97f8a671eff2cbe69c77508c2590011b3fdbf5c4ddecfcaacf9ad8aaff0e3cbb6a402908020971110c5e6e922c0172b01d84e9e9b78fc249ba5c

test:
  secret_key_base: 610ad06e19bfd3ed53aaf6868d1a33237067b0340690be8c609c6c2e4225d3ecc3c990be5e0817e9da0148be0a46be4ee88b1d4a4464ad9fbc7effbf9714ccd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
